### ISSUE TITLE
Make "Add Item" option available for each budget in the budget list.

### ISSUE THREAD

**Issue by shafeen** [shafeen/WhatCanISpend#4]
As it stands, `budgetId =  1` is hardcoded for the nav menu button "**Add item to budget**"  at the top of the interface, this is just temporary. 

**TODO**:
- [x] remove hardcoded "**Add item to budget**" button from the top of the interface
- [x] have an "**Add Item**" button be available for _each_ budget in the budget list
- [x] when "**Add Item**" is clicked, it should know/grab the `id`of the budget it is referring to from the list and use it in its `/budget/additem/` _POST_ request

**Comment by shafeen** [comment]
"Add Item" option is now available when you expand any budget's accordion (which will also reveal its current items, if any) from the list of budgets.

Removed the old hardcoded  "**Add item to budget**" button from the top of the interface.
